#!/bin/bash

source $(dirname $0)/helpers.sh
LOG=/tmp/log/$(basename $0).log
mkdir -p /tmp/log

(
  display Installing packages
  xargs yum -y install < /build/packages.txt

  display Installed versions:
  (
    git --version
    java -version
    ruby -v
    gem -v
    python -V
  ) | sed -u "s/^/      /"
) 2>&1 | tee $LOG

