#!/bin/bash

source $(dirname $0)/helpers.sh
LOG=/tmp/log/$(basename $0).log
mkdir -p /tmp/log

(
  display Installing packages
  xargs yum -y install < /build/packages.txt

  display Install buildpacks
  mkdir -p /build/buildpacks
  cd /build/buildpacks
  xargs -L 1 git clone --depth=1 < /build/buildpacks.txt

  display Installed versions:
  (
    git --version
    java -version
    ruby -v
    echo gem version `gem -v`
    python -V
  ) | sed -u "s/^/      /"
) 2>&1 | tee $LOG

