#!/bin/bash

source $(dirname $0)/helpers.sh
LOG=/tmp/log/$(basename $0).log
mkdir -p /tmp/log

(
  display Installing packages
  xargs yum -y install < /build/packages.txt
  ln -s /usr/lib64/libssl.so.10 /usr/lib64/libssl.so.0.9.8
  ln -s /usr/lib64/libcrypto.so.10 /usr/lib64/libcrypto.so.0.9.8

  display Install buildpacks
  (
    mkdir -p /build/buildpacks
    cd /build/buildpacks
    xargs -L 1 git clone --depth=1 < /build/buildpacks.txt
  ) 2>&1 | indent

  display Installed versions:
  (
    git --version
    java -version
    ruby -v
    echo gem version `gem -v`
    python -V
  ) 2>&1 | indent

) 2>&1 | tee $LOG

